# Generated by Django 3.2 on 2021-05-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='haihello', upload_to='galary'),
            preserve_default=False,
        ),
    ]
